# Generated by Django 4.1 on 2022-12-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='rest',
        ),
        migrations.AddField(
            model_name='food',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.AddField(
            model_name='menu',
            name='food',
            field=models.ManyToManyField(to='main.food'),
        ),
    ]
