# Generated by Django 4.1 on 2022-12-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menu_remove_rooms_rest_food_bio_delete_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'staff'), (3, 'user')]),
        ),
    ]
