# Generated by Django 4.1 on 2022-12-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='many',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'staff'), (3, 'user')], default=3),
        ),
    ]
