# Generated by Django 4.1 on 2022-12-04 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_staff_many_alter_user_passport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='end',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='start',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='user',
        ),
        migrations.AddField(
            model_name='rooms',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.rooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
