# Generated by Django 4.1 on 2022-12-04 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_rooms_end_remove_rooms_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='rooms')),
            ],
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='busy',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='number',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='img',
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('busy', models.BooleanField(default=False)),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rooms')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.description'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='img',
            field=models.ManyToManyField(to='main.images'),
        ),
    ]
