# Generated by Django 4.1 on 2022-12-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_images_remove_rooms_busy_remove_rooms_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='l_name',
            field=models.CharField(default=1, max_length=210),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='time',
            field=models.IntegerField(choices=[(1, 'Morning: from 8 a.m until 4 p.m'), (2, 'Afternoon: from 4 p.m until 0 p.m'), (3, 'Night: from 0 p.m until  8 a.m')]),
        ),
    ]
