# Generated by Django 4.1 on 2022-12-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_staff_l_name_alter_staff_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='ads',
            field=models.ManyToManyField(to='main.ads'),
        ),
    ]
