# Generated by Django 4.1 on 2022-12-05 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_hotelimage_remove_hotel_img_hotel_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
    ]
